# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 832b144c5d5f842e05475e2702f9a06a23d46d9a2c1de156e49324aa183aae70543c4d341756e474c83683ace984cc2e364cfd38b92532a1aeae7a3ec81f6101

test:
  secret_key_base: fb172b2afadebc27983553fcd2e38707067493a35841573327d5d4ab176cf7d56f9e3b04189e9a44fb878b966d903b62cbfdaf1d7396d1a602c937e3e0b263a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
